/* Tables */
CREATE TABLE SEANCE (
    ID_S INTEGER NOT NULL,
    NOM INTEGER ,
    TYPE INTEGER ,
    NIVEAU INTEGER ,
    PRIMARY KEY (ID_S)
);
CREATE TABLE ENTRAINEUR (
    CODEE INTEGER NOT NULL,
    PRENOM INTEGER,
    NOM INTEGER ,
    DATE_NAISS INTEGER ,
    EMAIL INTEGER ,
    NUMTELE INTEGER,
    PRIMARY KEY (CODEE)
);
CREATE TABLE HORAIRE (
    SEANCE_ID_S INTEGER ,
    ENTRAINEUR_CODEE INTEGER ,
    PRIMARY KEY (SEANCE_ID_S, ENTRAINEUR_CODEE),
    FOREIGN KEY (SEANCE_ID_S) REFERENCES SEANCE(ID_S),
    FOREIGN KEY (ENTRAINEUR_CODEE) REFERENCES ENTRAINEUR(CODEE)
);